#开发环境
#项目基本配置
dev:
  uname: jdr
  age: 18

# 开发环境配置
server:
  # 服务器HTTP端口，默认80
  port: 8082
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat最大线程数，默认200
    max-threads: 800
    # 启动Tomcat初始化的线程数，默认25
    min-spare-threads: 30

# Spring配置
spring:
  #数据源配置
  datasource:    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot_demo?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: root

# MyBatis配置
mybatis:  # 配置扫描指定包别名路径
  type-aliases-package: com.sb.demo.**.domain
  # 配置mapper的扫描路径，扫描所有的mapper.xml映射文件
  mapper-locations: classpath:mybatis/**/*Mapper.xml
  # 加载全局的配置文件
  #config-location: classpath:mybatis/mybatis-config.xml